apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: example
  labels:
    app: log-generator
spec:
  containers:
    - name: log-generator
      image: busybox
      args:
        [
          /bin/sh,
          -c,
          'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done',
        ]
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
